name: Deploy to GitHub Pages

on:
  push:
    branches: [ github-build ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
#        удалить этот блок
      - name: Debug secrets
        run: |
          echo "DEPLOY_TOKEN length: ${#DEPLOY_TOKEN}"
          echo "GITHUB_TOKEN length: ${#GITHUB_TOKEN}"
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./dist
          publish_branch: github-build